config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
     :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :movies,:tmdb_search,:reviews
  root to: 'movies#index'
  get 'search' => 'movie_from_tmdb#index' , as:'search'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/movie_from_tmdb.rb
class MovieFromTmdb < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
    #belong_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movie_from_tmdb_controller.rb
class MovieFromTmdbController < ApplicationController

    def index
        Tmdb::Api.key("1800a69a4e84911cbb0d843dea9ed085")
        Tmdb::Api.language("de")
        @search = Tmdb::Search.new
        @search.resource('movie') # determines type of resource
        @search.query(params[:search]) # the query to search against
        @movie_list = @search.fetch
        if (@movie_list)
          return @movie_list
        else
          return @movie_list = []
        end
    end

    def search
        Tmdb::Api.key("1800a69a4e84911cbb0d843dea9ed085")
        Tmdb::Api.language("de")
        @search = Tmdb::Search.new
        @search.resource('movie') # determines type of resource
        @search.query(params[:search]) # the query to search against
        @movie_list = @search.fetch
        @list_class = Array.new
        if (@movie_list)
          @movie_list.each do |movie|
            @movie_test = MovieFromTmdb.new(:title => movie['original_title'],:rating => movie['vote_average'],:release_date => movie['release_date'], :description => ' ')
            @movie_test.save
            @list_class.push(@movie_test)
          end
          @movie_list
        else
          @movie_list = []
        end
    end
    
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    
    before_action :set_movie, only: [:show, :edit, :update, :destroy]
    
    def home
    end
    def index
        @movies = Movie.all
    end

    def show
        @movies = Movie.find(params[:id])
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)
    
          if @movie.save
            #redirect_to movies_path(@movie), :notice => "Movie was successfully created."
            render "show" 
          else
            render "new"
          end
        
    end

    def edit
        @movies = Movie.find(params[:id])
    end

    def update
        
          if @movie.update(movie_params)
            render "show"
          else
            render "edit"
          end
        
    end

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy
        redirect_to movies_path, :notice => "Movie was successfully destroyed."
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :rating, :description, :release_date)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_from_tmdb_helper.rb
module MovieFromTmdbHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookkytomatoes</title>
    
 
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">


<style>

.bookkytomatoes{
  font-size: 300%;
  color: #c26565;
  cursor: pointer;
  background-color: inherit;
  border: none;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  text-shadow: 0 0 10px #FFFFFF, 2px 2px 2px rgba(206,89,55,0);
}

.bookkytomatoes:hover {background-color: #96bb7c;color: #f5f1da;}

.button_in_nav {
  background-color: #f5f1da;
  color: #c26565;
  border: 4px solid #c26565;
  padding: 4px 20px;
  font-size: 125%;
  border-radius: 12px;
  display: block;
  font-family: monaco,Consolas,Lucida Console,monospace;
  float: left;
  
}

.button_in_nav:hover {background-color: #c26565 ;color: white;}

.navbar {
  overflow: hidden;
  align-items: left;
  justify-content: left;
  background-color: #96bb7c;
}



.navbar a:hover {background-color: #96bb7c;color: #f5f1da;}

body{
  background-color: #c26565;
}


.button_home {
  background-color: #eebb4d;
  color: black;
  border: 2px solid #eebb4d;
  padding: 26px 20px;
  font-size: 100%;
  display: block;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  
}

.button_new {
  background-color: #f5f1da;
  color: #c26565;
  border: 4px solid #96bb7c;
  padding: 14px 20px;
  border-radius: 12px;
  font-size: 150%;
  font-family: monaco,Consolas,Lucida Console,monospace; 
}

.button_new:hover {background-color: #96bb7c;color: white;}

.button_table {
  background-color: white;
  color: #c26565;
  border: 2px solid #96bb7c;
  padding: 7px 15px;
  border-radius: 12px;
  font-size: 100%;
  font-family: monaco,Consolas,Lucida Console,monospace; 
}
.button_table:hover {background-color: #96bb7c;color: white;}

body{
  background-color: #c26565;
}

.center {
    display: flex;
    justify-content: center;
    align-items: center;
  }


  .left {
    display: flex;
    justify-content: left;
    align-items: left;
  }

  .box_table {
  width: 70%;
  padding: 10px;
  margin: 0;
}

h1{
  font-family: monaco,Consolas,Lucida Console,monospace; 
}

label{
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 125%;
}

.c_show{
  font-size: 125%;
}

.movie-form {
  display: flex;
  width: 30%;
  flex-direction: column;
  align-items: center;
  padding: 50px 40px;
  color: #c26565;
  background: #f5f1da;
  border-radius: 10px;
  border: 7px groove #96bb7c;
  font-family: monaco,Consolas,Lucida Console,monospace; 

  h1 {
    margin: 0 0 24px 0;
  }

  .form-input-material {
    margin: 12px 0;
  }

  .btn {
    width: 100%;
    margin: 18px 0 9px 0;
  }
}

#table-scroll {
  
  overflow:auto;  
  margin-top:20px;
}

.number_rating{
  placeholder:1-10
}

.button_submit {
  background-color: #f5f1da ;
  color: #96bb7c;
  border: 4px solid #96bb7c;
  padding: 14px 40px;
  border-radius: 12px;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 125%;
}

.button_submit:hover {background-color: #96bb7c;color: white;}

.button_back {
  background-color: #f5f1da ;
  color: #c26565;
  border: 4px solid #c26565;
  padding: 14px 40px;
  border-radius: 12px;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 125%;
}

.button_back:hover {background-color: #c26565 ;color: white;}

.button_search {
  background-color: #f5f1da ;
  color: #c26565;
  border: 4px solid #c26565;
  padding: 4px 20px;
  border-radius: 12px;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 125%;
}

.button_search:hover {background-color: #c26565 ;color: white;}

.button_delete {
  background-color: #f5f1da ;
  color: #eebb4d;
  border: 4px solid #eebb4d ;
  padding: 14px 40px;
  border-radius: 12px;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 125%;
}

.button_delete:hover {background-color: #eebb4d ;color: white;}

.button_sign_in {
  background-color: #f5f1da ;
  color: #96bb7c;
  border: 4px solid #96bb7c ;
  padding: 7px 20px;
  border-radius: 12px;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 100%;
}

.button_sign_in:hover {background-color: #96bb7c ;color: white;}

.button_log_in {
  background-color: #f5f1da ;
  color: #eebb4d;
  border: 4px solid #eebb4d ;
  padding: 7px 20px;
  border-radius: 12px;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 100%;
}

.button_log_in:hover {background-color: #eebb4d ;color: white;}

.button_sign_in_facebook {
  background-color: #f5f1da ;
  color: #3B5998;
  border: 4px solid #3B5998 ;
  padding: 7px 20px;
  border-radius: 12px;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 100%;
}

.button_sign_in_facebook:hover {background-color: #3B5998 ;color: white;}

.button_sign_in_facebook_main {
  background-color: #f5f1da ;
  color: #3B5998;
  border: 4px solid #3B5998 ;
  padding: 14px 40px;
  border-radius: 12px;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 150%;
}

.button_sign_in_facebook_main:hover {background-color: #3B5998 ;color: white;}

.fa-facebook {
  background: #3B5998;
  color: white;
  padding: 7px 20px;
  border-radius: 12px;
  font-family: monaco,Consolas,Lucida Console,monospace; 
  font-size: 100%;
}

table{
  font-family: Cambria,Georgia,serif; 
  font-size: 125%;
}



</style>

<% if current_user %>
  <div> <%= current_user.name %></div>
  <% end %>
<% unless current_user %>
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
<% else %>
<div class="navbar">
<%= link_to '<button class="bookkytomatoes">BOOKKYTOMATOES</button>'.html_safe, movies_path %>
&emsp;&emsp;&emsp;&emsp;
<%= link_to '<button class="button_in_nav">Add New Movie</button>'.html_safe, new_movie_path %> 
&emsp;
<%= link_to '<button class="button_in_nav">Review Movie</button>'.html_safe, reviews_path %>  
  
</div>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% end %>






<p id="notice"><%= notice %></p>  
    </head>
  

  <body>
    <%= yield %>
  </body>
</html>

app/views/movie_from_tmdb/index.html.erb
<br />
<H1><center><font color="#96bb7c"><B>Search Movie from TheMovieDb</B></font></center></H1>
<br />

  <div class="center">
<div class="box_table">
<div class="table-wrapper-scroll-y my-custom-scrollbar">
<table class="table table-hover" width="70%" border="5px" bgcolor="#96bb7c" padding="15px">
  <thead>
    <tr>
    <th >Title</th>
    <th >Rating</th>
    <th >Release Date</th>
    </tr>
  </thead>

  <tbody bgcolor="#f5f1da">
    <% @movie_list.each do |movie| %>
      <tr>
      <td padding: 15px ><img src="https://image.tmdb.org/t/p/w500/<%= movie['poster_path'] %>" alt="" height="30%"><br><%= movie['title'] %></td>
      <td padding: 15px><%= movie['vote_average'] %></td>
      <td padding: 15px><%= movie['release_date'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div> 
</div> 


<br>

app/views/movies/edit.html.erb
<div class="center">
<div class="movie-form">
<%= form_for @movie,html: {class: "movie-form"} do |f| %>
    <h1>Edit Movie</h1>
    <br>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    
    <%= f.label :rating %>
    <%= f.number_field :rating, in: 1.0..10.0, step: 0.1 , placeholder: "1-10" %>

    <br>
    <%= f.label :description %>
    <%= f.text_area :description, cols: "30" , rows: "4"%>
    <br>
    <%= f.label :release_date %>
    <%= f.date_field :release_date ,min: "1930-12-31" ,max: "2020-10-20" %>
    <br>
    <br>
    <div>
    <%= f.submit :SUBMIT ,class: "button_submit"%>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    <%= link_to '<button class="button_back">CANCEL</button>'.html_safe, movies_path(@movie) %>
    </div>
    <br>
    <br>
    
    
<% end %>
</div>
</div>

app/views/movies/home.html.erb
<% unless current_user %>
    <div class="movie-form">
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    </div>
  <% else %>
<%= link_to '<button class="bookkytomatoes">BOOKKYTOMATOES</button>'.html_safe, movies_path %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% end %>

app/views/movies/index.html.erb
<body>

  <br>
  <div class="center">
  <%= form_tag search_path, :method => 'get' do %>

    <%= text_field_tag :search, params[:search] ,:class => 'input_search' %>
    <%= submit_tag "Search" ,:class => 'button_search' ,:autocomplete => "off"%>
    <% end %>
  </div>

<br>
<div class="center">
<div class="box_table">
<div class="table-wrapper-scroll-y my-custom-scrollbar">
<table class="table table-hover" width="70%" border="5px" bgcolor="#96bb7c" padding="15px">
  <thead>
    <tr>
    <th >Title</th>
    <th >Rating</th>
    <th colspan="1"></th>
    </tr>
  </thead>

  <tbody bgcolor="#f5f1da">
    <% @movies.each do |movie| %>
      <tr>
      <td padding: 15px ><%= movie.title %></td>
      <td padding: 15px><%= movie.rating %></td>
      <td padding: 15px><%= link_to '<button class="button_table">Show</button>'.html_safe, movie %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div> 
</div> 



<br>

</body>

app/views/movies/new.html.erb
<br>

<div class="center">

<%= form_for @movie,html: {class: "movie-form"} do |f| %>
    <h1>New Movie</h1>
    <br>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    
    <%= f.label :rating %>
    <%= f.number_field :rating, in: 1.0..10.0, step: 0.1 , placeholder: "1-10" %>

    <br>
    <%= f.label :description %>
    <%= f.text_area :description, cols: "30" , rows: "4"%>
    <br>
    <%= f.label :release_date %>
    <%= f.date_field :release_date ,min: "1930-12-31" ,max: "2020-10-20" %>
    <br>
    <br>
    <div>
    <%= f.submit :ADD ,class: "button_submit"%>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    <%= link_to '<button class="button_back">Back</button>'.html_safe, movies_path %>
    </div>
    <br>
    <br>
<% end %>

</div>

app/views/movies/show.html.erb
<br>
<br>
<br>
<br>
<br>

<body>
<div class="center">
<div class="movie-form">
<p class="c_show" style="text-align:center">
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p class="c_show" style="text-align:center">
  <strong>Rating:</strong>
  <%= @movie.rating %>
</p>

<p class="c_show" style="text-align:center">
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p class="c_show" style="text-align:center">
  <strong>Release date:</strong>
  <%= @movie.release_date %>
</p>
<br>
<div class="center">
<%= link_to '<button class="button_submit">Edit</button>'.html_safe, edit_movie_path(@movie) %>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
<%= link_to '<button class="button_delete">Delete</button>'.html_safe, @movies,:method => :delete %>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
<%= link_to '<button class="button_back">Back</button>'.html_safe, movies_path(@movie) %>
</div>
</div>ssssss
</div>
</body>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>